name: Deploy on Push

on:
  push:
    branches:
      - "*"  # Trigger workflow on push to the any branch in repo

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get commit ID and branch
      id: vars
      run: |
        echo "COMMIT_ID=$(git rev-parse HEAD)" >> $GITHUB_ENV
        echo "BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV

    - name: Trigger deployment
      run: |
        curl -X POST http://35.230.101.155:8969/deploy \
          -H "Content-Type: application/json" \
          -d '{"commit_id": "${{ env.COMMIT_ID }}", "branch": "${{ env.BRANCH_NAME }}"}'
